apiVersion: v1
kind: Namespace
metadata:
  name: nm

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nm_default_sa_role
  namespace: nm
rules:
- apiGroups: ["*"]
  resources: ["pods", "services"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: "RoleBinding"
metadata:
  name: nm_default_sa_rolebinding
  namespace: nm
subjects:
- kind: ServiceAccount
  name: default
  namespace: nm
roleRef:
  kind: Role
  name: nm_default_sa_role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nm-dataset-volume
  namespace: nm
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500M
  hostPath:
    path: /data/pv0001/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nm-dataset-claim
  namespace: nm
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M